source 'https://rubygems.org'
# source 'http://ruby.taobao.org/'

gem 'dun'
gem 'ground'
gem 'sqlite3'
gem 'pg'
gem 'rack'
gem 'haml'
gem 'tilt'
gem 'sequel'
gem 'json'
gem 'bcrypt-ruby', require: 'bcrypt'
gem 'sanitize'
gem 'unicorn'
gem 'thin'
gem 'puma'
gem 'rake'