source 'https://rubygems.org'
# source 'http://ruby.taobao.org/'

gem 'dun'
gem 'ground', :git => 'git://github.com/baya/ground.git'
gem 'sqlite3'
gem 'pg'
gem 'rack'
gem 'haml'
gem 'tilt'
gem 'sequel'
gem 'json'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'sanitize'
gem 'unicorn'
gem 'thin'
gem 'puma'