source 'https://rubygems.org'
# source 'http://ruby.taobao.org/'

gem 'dun'
#gem 'ground', git: 'git://github.com/baya/ground.git', ref: '481c7bf9'
gem 'sqlite3'
gem 'pg'
#gem 'rack'
gem 'haml'
gem 'tilt'
gem 'sequel'
gem 'json'
gem 'bcrypt-ruby', require: 'bcrypt'
gem 'sanitize'
gem 'unicorn'
gem 'thin'
gem 'puma'
gem 'rake'