development:
  adapter: postgres
  database: scene_development
  host: localhost
  user: scene
  password: none
  max_connections: 5
  pool_timeout: 5000

development:
  adapter: sqlite
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
